### ISSUE TITLE
샘플링 시 고려해야할 점들

### ISSUE THREAD

**Issue by l-yohai** [Gaepodong/automatic_tagging_review_ratings#3]
샘플링을 거치고 나니까 확실히 속도는 매우 빨라지고 다양한 댓글들이 보이기 시작했습니다.
하지만 어떤 방식의 샘플링을 채택해야 할 지에 대한 고민이 필요할 것 같습니다.

우선 긍/부정을 나누지 않은 전체 댓글을 대상으로 진행했고,
단순히 문장 길이만 가지고 샘플링을 해서 랭킹을 매겨보았습니다.

```python
def sampling_texts(texts, length):
    for i in range(len(texts)):
        if (len(str(texts[i])) > length):
            samples.append(str(texts[i]))
    return samples

length = 130 # 현재 데이터셋에서 길이가 130 이상인 댓글이 약 2000개 정도 나왔기에 초기값 130으로 지정.
if len(texts) > 1000:
    samples = []
    while len(samples) < 1000:
        samples = sampling_texts(texts, length)
        length -= 10
else:
    samples = []
    for i in range(len(texts)):
        samples.append(str(texts[i]))
```

### 품사태깅한 길이가 500이 넘는 문장들 (약 200개)
![image](https://user-images.githubusercontent.com/49181231/91887386-afc72d80-ecc5-11ea-9c21-eed84fe19c71.png)
-> 길이가 짧은 문장 중에서도 극성이 드러나는 문장들이 나타났음.
-> 대부분 부정에 가까운 문장들임.

### 품사태깅한 문장들 중 길이가 400이 넘는 문장들(약 2600개)
![image](https://user-images.githubusercontent.com/49181231/91887503-d1c0b000-ecc5-11ea-9391-5c39b9859ec8.png)
-> 역시나 극성이 잘 나타나는 문장들이 대부분 선택되었으나, 대부분 부정에 가까움.

### 품사태깅하지 않은 문장들 중 길이가 130이 넘는 문장들 (약 2000개) -> 품사태깅도 약 2천개만 진행
![image](https://user-images.githubusercontent.com/49181231/91890891-1733ac00-eccb-11ea-82fc-56c953e42a1a.png)
-> 10개정도의 댓글들을 추려보았을 때 애초에 긴 문장들만 가지고 진행해서 나름 대표성이 있다고 생각해볼 수 있음.
-> 그러나 랭킹수치가 매우 낮음. (댓글이 길기 때문에 랭킹이 높은 단어들 이외의 단어들이 등장했고, 그 단어들과 유사도가 낮기 때문인듯)

1. 댓글수를 고려하지 못하는 상황일 때를 대비해야 할 것 같음
- 코드에서는 조건을 걸어서 1000개 이상인 리스트가 만들어지면 빠져나오도록 하였으나
- 예를들어 댓글이 200개정도인 영화 -> 대부분이 댓글 길이가 적을 것이기 때문에 저번주에 의논했던 문제들(댓글이 매우 짧거나 극성이 거의 보이지 않는...)
2. 품사태깅한 문장들로 진행할 경우 짧은 문장도 대체로 섞여나오기 때문에 극성이 드러난 문장들을 찾아낼 수 있음. 반면 애초에 길이가 긴 문장들로 진행할 시 품사태깅하는 문장들도 적어지기 때문에 시간면에서는 매우 빠르나 그저 긴 문장들을 랜덤으로 뽑은것 같은 느낌..?

**Comment by humblEgo** [comment]
넘 수고 많으셨습니다! 추측으로 말씀드리는 코멘트..

1. 저희가 확정한 방법대로라면, 분석할 영화페이지를 저희가 선택하는 상황이니까 댓글 수가 적은 경우를 고려한 방법까지 생각해야하나 싶습니다. 이와 별개로 min(댓글 수, 1000) 조건보다 sample 수가 많아지면 루프를 빠져나오게하면 되지 않을까요?

2. 우선 처리하는데 걸리는 속도는 샘플링 방법 고려시에 제외해도 될 것 같습니다. 저희가 확정한 방법은 현재 실시간으로 샘플링하는 서비스가 아니고, 미리 샘플링해둔 댓글을 보여주는 식이니까 공모전 제출일 이전에 샘플링을 완료할 수 있는 속도라면, 그대로 진행해도 될 것 같습니다.

5개 문장을 뽑을 때 2개는 '품사태깅한 문장들로 진행' 한 문장을, 나머지 3개 문장을 뽑을 때는 '애초에 길이가 긴 문장들로 진행'한 문장을 뽑고, 둘 사이에 중복이 없도록 하면 되지 않을까 싶은데 넘 복잡할까요??

**Comment by l-yohai** [comment]
코멘트 감사합니다!

우선 애초에 코드 자체에 실수가 있었네요... 핳
샘플링 된 리스트의 인덱스를 전체 텍스트의 인덱스로 활용해서 결과와 다른 길이가 짧은 문장들이 나왔던 거였습니다....!
혼란을 드려 죄송합니다.....

말씀하신대로 댓글 비율을 2개 3개로 나누어 조정해보도록 하겠습니다.
길이가 짧으나 극성이 높은 문장들을 포함시키려면 전체 텍스트의 랭크를 계산하긴 해야 할 것 같습니다.
(시간을 줄이려면 지금 사용하는 min값을 절반정도로 줄여도 괜찮은 결과가 나올 것 같긴 합니다.)
